name: Feature Request
description: Suggest a new feature or enhancement for the W Prime Extension
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New W Prime algorithm
        - UI/UX improvement
        - Data field visualization
        - Integration with other platforms
        - Configuration option
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: "I would like the extension to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Another approach could be..."
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature improve your cycling or training?
      placeholder: |
        During races, I would benefit from...
        While training, this would help me...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Screenshots, links to similar features, scientific papers, etc.
    validations:
      required: false

